# Generated by Django 4.2.3 on 2023-07-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0003_alter_product_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kind',
            field=models.CharField(choices=[('technology', 'Technology'), ('fashion', 'Fashion'), ('healthbeauty', 'Health and Beauty'), ('toy', 'Toy'), ('fitness', 'Fitness'), ('food', 'Food')], default='technology', max_length=100),
        ),
    ]
